services:
  - serviceId: zss
    title: Zowe System Services (ZSS)
    description: 'Zowe System Services is an HTTPS and Websocket server that makes it easy to have secure, powerful web APIs backed by low-level z/OS constructs. It contains services for essential z/OS abilities such as working with files, datasets, and ESMs, but is also extensible by REST and Websocket "Dataservices" which are optionally present in App Framework "Plugins".'
    catalogUiTileId: zss
    instanceBaseUrls:
      - https://RS28.rocketsoftware.com:61998/
    homePageRelativeUrl:
    routedServices:
      - gatewayUrl: api/v1
        serviceRelativeUrl: 
    apiInfo:
      - apiId: zowe.zss
        gatewayUrl: api/v1
        swaggerUrl: https://RS28.rocketsoftware.com:61999/api-docs/agent
catalogUiTiles:
  zss:
    title: Zowe System Services (ZSS)
    description:  Zowe System Services is an HTTPS and Websocket server that makes it easy to have secure, powerful web APIs backed by low-level z/OS constructs.
