spring.profiles.include: diag

apiml:
    service:
        hostname: localhost
        ipAddress: 0.0.0.0
        port: 10011
    discovery:
        staticApiDefinitionsDirectories: config/local/api-defs
        allPeersUrls: https://localhost2:10021/eureka
    security:
        ssl:
            verifySslCertificatesOfServices: true
    banner: console

spring:
    output:
        ansi:
            enabled: always

---
spring.profiles: https

server:
    ssl:
        keyAlias: localhost-multi
        keyPassword: password
        keyStoreType: PKCS12
        keyStore: keystore/localhost/localhost-multi.keystore.p12
        keyStorePassword: password
        trustStoreType: PKCS12
        trustStore: keystore/localhost/localhost-multi.truststore.p12
        trustStorePassword: password

apiml:
    discovery:
        allPeersUrls: https://localhost2:10021/eureka
