spring.profiles.include: diag

apiml:
    service:
        hostname: localhost
        ipAddress: 127.0.0.1
        port: 10011
    discovery:
        staticApiDefinitionsDirectories: config/local/api-defs
    security:
        ssl:
            verifySslCertificatesOfServices: false
    banner: console

spring:
    output:
        ansi:
            enabled: always

---
spring.profiles: https
eureka:
    client:
        initialInstanceInfoReplicationIntervalSeconds: 1
        registryFetchIntervalSeconds: 1

server:
    ssl:
        keyAlias: localhost
        keyPassword: password
        keyStoreType: PKCS12
        keyStore: keystore/localhost/localhost.keystore.p12
        keyStorePassword: password
        trustStoreType: PKCS12
        trustStore: keystore/localhost/localhost.truststore.p12
        trustStorePassword: password
---
spring:
    profiles: attls

apiml:
    discovery:
        staticApiDefinitionsDirectories: config/local/api-defs-http

