spring.profiles.include: diag

environment:
    discoveryLocations: http://eureka:password@localhost:10011/eureka/
    dsIpAddress: 127.0.0.1
    gatewayHostname: localhost
    gatewayTimeoutInMillis: 30000
    hostname: localhost
    ipAddress: 127.0.0.1
    keyAlias: localhost
    keyPassword: password
    keystore: keystore/local/localhost_server.jks
    keystorePassword: password
    keystoreType: JKS
    port: 10010
    preferIpAddress: false
    scheme: https
    sslEnabled: true
    truststore: keystore/local/localhost_truststore.jks
    truststorePassword: trustword
    truststoreType: JKS

mfaas:
    gateway:
        verifySslCertificatesOfServices: false

eureka:
    client:
        initialInstanceInfoReplicationIntervalSeconds: 5
        registryFetchIntervalSeconds: 5
    instance:
        leaseExpirationDurationInSeconds: 6
        leaseRenewalIntervalInSeconds: 5

spring:
    output:
        ansi:
            enabled: always
