spring.profiles.include: diag
apiml:
    service:
        hostname: localhost
        ipAddress: 127.0.0.1
        port: 10010
        discoveryServiceUrls: https://localhost:10011/eureka/
    security:
        auth:
            provider: dummy
            zosmfServiceId: zosmf  # Replace me with the correct z/OSMF service id
        ssl:
            verifySslCertificatesOfServices: true
        jwt:
            signatureAlgorithm: HS512
            secretKey:

spring:
    output:
        ansi:
            enabled: always

server:
    ssl:
        keyAlias: localhost
        keyPassword: password
        keyStore: keystore/localhost/localhost.keystore.p12
        keyStorePassword: password
        keyStoreType: PKCS12
        trustStore: keystore/localhost/localhost.truststore.p12
        trustStorePassword: password
        trustStoreType: PKCS12
