spring.profiles.include: diag
apiml:
    service:
        hostname: localhost
        ipAddress: 127.0.0.1
        port: 10010
        discoveryServiceUrls: https://localhost:10011/eureka/
    security:
        auth:
            provider: zosmf
            zosmf:
                serviceId: mockzosmf  # Replace me with the correct z/OSMF service id
            passTicket:
                timeout: 360 # [s] - default timeout to expire (z/OS has 10 mins as default)
        ssl:
            verifySslCertificatesOfServices: false
        x509:
            enabled: true
    banner: console

eureka:
    client:
        initialInstanceInfoReplicationIntervalSeconds: 1
        registryFetchIntervalSeconds: 1
spring:
    output:
        ansi:
            enabled: always
    cache:
        ehcache:
            config: classpath:ehcache.xml

server:
    internal:
        enabled: true
        port: 10017
        ssl:
            keyAlias: localhost-multi
            keyStore: keystore/localhost/localhost-multi.keystore.p12
    ssl:
        keyAlias: localhost
        keyPassword: password
        keyStore: keystore/localhost/localhost.keystore.p12
        keyStorePassword: password
        keyStoreType: PKCS12
        trustStore: keystore/localhost/localhost.truststore.p12
        trustStorePassword: password
        trustStoreType: PKCS12

---
spring:
    profiles: attls

apiml:
    service:
        scheme: http
        discoveryServiceUrls: http://localhost:10001/eureka/

