resourcePackages:
    - com.ca.hwsjersey.resource
prettyPrint: true
cacheTTL: 0
openapi: 3.0.0
info:
    version: '1.0.0'
    title: Hello World Jersey
    description: 'REST API for a Jersey Application'
servers:
    - url: https://localhost:10016/hellojersey
