serviceId: hellospring
title: Hello Spring REST API
eureka:
    hostname: localhost
    ipAddress: 127.0.0.1
    port: 10021
description: Example for exposing a Spring REST API
baseUrl: http://localhost:10021/hellospring
homePageRelativeUrl:
statusPageRelativeUrl: /application/info
healthCheckRelativeUrl: /application/health
discoveryServiceUrls:
    - https://localhost:10011/eureka
ssl:
    verifySslCertificatesOfServices: true
    protocol: TLSv1.2
    keyAlias: localhost
    keyPassword: password
    keyStore: ../keystore/localhost/localhost.keystore.p12
    keyStorePassword: password
    keyStoreType: PKCS12
    trustStore: ../keystore/localhost/localhost.truststore.p12
    trustStorePassword: password
    trustStoreType: PKCS12
routes:
    - gatewayUrl: api
      serviceUrl: /hellospring
    - gatewayUrl: api/v1
      serviceUrl: /hellospring/api/v1
    - gatewayUrl: api/v1/api-doc
      serviceUrl: /hellospring/api-doc
apiInfo:
    - apiId: org.zowe.hellospring
      gatewayUrl: api/v1
      swaggerUrl: http://localhost:10021/hellospring/api-doc
catalog:
    tile:
        id: cademoapps
        title: Sample API Mediation Layer Applications
        description: Applications which demonstrate how to make a service integrated to the API Mediation Layer ecosystem
        version: 1.0.0
