services:

    redis-master:
        container_name: redis-master
        image: redis:latest
        command: redis-server /usr/local/etc/redis/master-tls.conf
        ports:
            - "6379:6379"
        volumes:
            - ../keystore:/usr/local/etc/keystore
            - ./master:/usr/local/etc/redis/

    redis-replica:
        container_name: redis-replica
        image: redis:latest
        command: redis-server /usr/local/etc/redis/replica-tls.conf
        ports:
            - "6380:6380"
        volumes:
            - ../keystore:/usr/local/etc/keystore
            - ./replica:/usr/local/etc/redis/
        links:
            - redis-master
