name: Image specific release

on:
    workflow_dispatch:
        inputs:
            release_version:
                description: 'The version that is going to be release'
                required: true

jobs:
    build-test-services:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
                with:
                    ref: ${{ github.head_ref }}

            -   uses: ./.github/actions/setup

            -   name: Build and test services
                run: ./gradlew build

            -   uses: ./.github/actions/teardown

    publish-images:
        needs:
            - build-test-services
        uses: zowe/api-layer/.github/workflows/build-conformant-images.yml@v1.x.x
        with:
            version: ${{ github.event.inputs.release_version }}
        secrets:
            registry-user: ${{ secrets.ARTIFACTORY_X_USERNAME }}
            registry-password: ${{ secrets.ARTIFACTORY_X_PASSWORD }}
            redhat-registry-user: ${{ secrets.REDHAT_DEVELOPER_USER }}
            redhat-registry-password: ${{ secrets.REDHAT_DEVELOPER_PASSWORD }}
            zlinux-host: ${{ secrets.ZLINUX_HOST }}
            zlinux-ssh-user: ${{ secrets.ZLINUX_SSH_USER }}
            zlinux-ssh-key: ${{ secrets.ZLINUX_SSH_KEY }}
            zlinux-ssh-passphrase: ${{ secrets.ZLINUX_SSH_PASSPHRASE }}
